server:
  port: 3231
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_login_test?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false
    username: root
    password: gaozhenlin233
    driver-class-name: com.mysql.cj.jdbc.Driver
